# services:
#   frontend:
#     build: ./Frontend
#     ports:
#       - "3000:3000"
#     volumes:
#       - ./Frontend:/app
#     depends_on:
#       - backend

#   backend:
#     build: ./Backend/app
#     ports:
#       - "3001:3001"
#     volumes:
#       - ./Backend/app:/app

services:
  frontend:
    build: ./Frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./Backend/app
    ports:
      - "3001:3001"